-- MySQL Script generated by MySQL Workbench
-- Tue Apr  1 14:10:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb_task_001_lvl_02
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb_task_001_lvl_02
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb_task_001_lvl_02` DEFAULT CHARACTER SET utf8 ;
USE `mydb_task_001_lvl_02` ;

-- -----------------------------------------------------
-- Table `mydb_task_001_lvl_02`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_task_001_lvl_02`.`employee` (
  `employee_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `phone` INT NOT NULL,
  `nif` VARCHAR(15) NOT NULL,
  `employee_typee` ENUM("cook", "delivery") NOT NULL,
  PRIMARY KEY (`employee_id`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_task_001_lvl_02`.`shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_task_001_lvl_02`.`shop` (
  `shop_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `code` INT NOT NULL AUTO_INCREMENT,
  `address` INT NOT NULL,
  UNIQUE INDEX `code_UNIQUE` (`code` ASC),
  CONSTRAINT `fk_employee_shop`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mydb_task_001_lvl_02`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_task_001_lvl_02`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_task_001_lvl_02`.`address` (
  `address_id` INT NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  `floor` INT NULL,
  `door` VARCHAR(5) NULL,
  `city_id` INT NOT NULL,
  `province_id` INT NOT NULL,
  `country_id` INT NOT NULL,
  `postal_code` INT NOT NULL,
  PRIMARY KEY (`address_id`),
  CONSTRAINT `fk_shop_address`
    FOREIGN KEY ()
    REFERENCES `mydb_task_001_lvl_02`.`shop` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_task_001_lvl_02`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_task_001_lvl_02`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `address_id` INT NOT NULL,
  `phone` INT NULL,
  PRIMARY KEY (`customer_id`),
  INDEX `fk_address_customer_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_address_customer`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb_task_001_lvl_02`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_task_001_lvl_02`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_task_001_lvl_02`.`city` (
  `city_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `code` INT NOT NULL,
  `province_id` INT NOT NULL,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  CONSTRAINT `fk_address_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb_task_001_lvl_02`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
PACK_KEYS = DEFAULT
ROW_FORMAT = FIXED;


-- -----------------------------------------------------
-- Table `mydb_task_001_lvl_02`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_task_001_lvl_02`.`province` (
  `province_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `code` INT NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  INDEX `fk_address_province_idx` (`province_id` ASC) VISIBLE,
  CONSTRAINT `fk_city_province`
    FOREIGN KEY (`province_id`)
    REFERENCES `mydb_task_001_lvl_02`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_province`
    FOREIGN KEY (`province_id`)
    REFERENCES `mydb_task_001_lvl_02`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_task_001_lvl_02`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_task_001_lvl_02`.`country` (
  `country_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `iso_UNIQUE` (`code` ASC) VISIBLE,
  INDEX `fk_province_country_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_province_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb_task_001_lvl_02`.`province` (`province_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb_task_001_lvl_02`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_task_001_lvl_02`.`salesorder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_task_001_lvl_02`.`salesorder` (
  `salesorder_id` INT NOT NULL,
  `salesorder_number` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL,
  `close_date` VARCHAR(45) NULL,
  `delivery_method` ENUM("home", "store") NOT NULL,
  `quanitiy` DECIMAL NULL,
  `price` DECIMAL NULL,
  `employee_id` INT NULL,
  `shop_id` INT NULL,
  PRIMARY KEY (`salesorder_id`),
  UNIQUE INDEX `salesorder_number_UNIQUE` (`salesorder_number` ASC) VISIBLE,
  INDEX `fk_customer_salesorder_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_employee_salesorder_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_salesorder`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb_task_001_lvl_02`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_salesorder`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb_task_001_lvl_02`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_task_001_lvl_02`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_task_001_lvl_02`.`product` (
  `product_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `image` BLOB NULL,
  `price` DECIMAL NOT NULL,
  `parent_product` INT NULL,
  `code` INT NOT NULL,
  `product_category_id` INT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_task_001_lvl_02`.`product_has_salesorder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_task_001_lvl_02`.`product_has_salesorder` (
  `product_product_id` INT NOT NULL,
  `salesorder_salesorder_id` INT NOT NULL,
  `quantity` VARCHAR(45) NULL,
  PRIMARY KEY (`product_product_id`, `salesorder_salesorder_id`),
  INDEX `fk_product_has_salesorder_salesorder1_idx` (`salesorder_salesorder_id` ASC) VISIBLE,
  INDEX `fk_product_has_salesorder_product1_idx` (`product_product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_salesorder_product1`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `mydb_task_001_lvl_02`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_salesorder_salesorder1`
    FOREIGN KEY (`salesorder_salesorder_id`)
    REFERENCES `mydb_task_001_lvl_02`.`salesorder` (`salesorder_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_task_001_lvl_02`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_task_001_lvl_02`.`product_category` (
  `product_category_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `code` INT NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX `code_UNIQUE` (`code` ASC),
  CONSTRAINT `fk_product_product_category`
    FOREIGN KEY (`product_category_id`)
    REFERENCES `mydb_task_001_lvl_02`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
